kind: pipeline
name: default

steps:
- name: xxx
  image: python:3.6-alpine
  commands:
  - python -c 'import sys; sys.exit(0)'

- name: stress-tool
  image: polinux/stress
  commands:
  - stress --cpu 4 --timeout 120s
